title: "The Wandering Tingan Sob"
description: "The Stories of an Urban Shaman"
about: "Performance art for the modern medicine man trapped in the Urban Jungle"
location: "The Planet Brooklyn"
email: tingansob@gmail.com
baseurl: "/the-wandering-tingansob"
url: "https://tingansob.github.com/the-wandering-tingansob/"
author: Ishmael BabaGaia

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
name_badge: "Brought to you by"

# build settings
markdown: kramdown
hoghlighter: rogue

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  footnote_nr: 1
  entitiy_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rogue
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-bootstrap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
